CREATE TABLE tmp(name TEXT, name2 TEXT, type TEXT);
INSERT INTO tmp SELECT DISTINCT * FROM articles;
DROP TABLE articles;
ALTER TABLE tmp RENAME TO articles;
ALTER TABLE articles ADD COLUMN _id BIGSERIAL PRIMARY KEY;