#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

# TODO would be nice to not have this list present in two places
all_categories = {
    1: unicode(u'Alkoholfritt'),
    2: unicode(u'Aniskryddad sprit'),
    3: unicode(u'Aperitif'),
    4: unicode(u'Armagnac'),
    5: unicode(u'Bitter'),
    6: unicode(u'Blanddrycker'),
    7: unicode(u'Brandy'),
    8: unicode(u'Vinsprit'),
    9: unicode(u'Calvados'),
    10: unicode(u'Cider'),
    11: unicode(u'Cognac, Konjak'),
    12: unicode(u'Drinkar och Cocktails'),
    13: unicode(u'Fruktvin'),
    14: unicode(u'Genever'),
    15: unicode(u'Gin'),
    16: unicode(u'Glögg och Glühwein'),
    17: unicode(u'Grappa'),
    18: unicode(u'Kryddad sprit'),
    19: unicode(u'Kaffelikör, Chokladlikör'),
    20: unicode(u'Fruktlikör, Bärlikör'),
    21: unicode(u'Gräddlikör, Ägglikör'),
    22: unicode(u'Kryddlikör, Örtlikör'),
    23: unicode(u'Likör'),
    24: unicode(u'Madeira'),
    25: unicode(u'Mjöd'),
    26: unicode(u'Montilla'),
    27: unicode(u'Mousserande vin, Champagne'),
    28: unicode(u'Vodka'),
    29: unicode(u'Portvin'),
    30: unicode(u'Punsch'),
    31: unicode(u'Rom, Ljus rom'),
    32: unicode(u'Rom, Mörk rom'),
    33: unicode(u'Rom'),
    34: unicode(u'Rosé, Rosévin'),
    35: unicode(u'Vin, Rött vin'),
    36: unicode(u'Sake'),
    37: unicode(u'Sherry'),
    38: unicode(u'Smaksatt sprit'),
    39: unicode(u'Smaksatt vin'),
    40: unicode(u'Sprit av frukt'),
    41: unicode(u'Tequila, Mezcal'),
    42: unicode(u'Vermouth'),
    43: unicode(u'Vin av flera typer'),
    44: unicode(u'Vin, Vitt vin'),
    45: unicode(u'Whisky, Whiskey'),
    46: unicode(u'Öl'),
    47: unicode(u'Öl, Ljus öl'),
    48: unicode(u'Öl, Mörk öl'),
    49: unicode(u'Övrig sprit'),
    50: unicode(u'Övrigt starkvin'),
}

specific_type_mappings = {
    'alkoholfritt': all_categories[1],
    'aniskryddad sprit': all_categories[2],
    'aperitif': all_categories[3],
    'armagnac': all_categories[4],
    'bitter': all_categories[5],
    'blanddrycker': all_categories[6],
    'brandy': all_categories[7],
    'vinsprit': all_categories[8],
    'calvados': all_categories[9],
    'cider': all_categories[10],
    'cognac': all_categories[11],
    'konjak': all_categories[11],
    'drinkar och cocktails': all_categories[12],
    'fruktvin': all_categories[13],
    'genever': all_categories[14],
    'gin': all_categories[15],
    'glögg och glühwein': all_categories[16],
    'grappa': all_categories[17],
    'kryddad sprit': all_categories[18],
    'kaffelikör': all_categories[19],
    'chokladlikör': all_categories[19],
    'bärlikör': all_categories[20],
    'fruktlikör': all_categories[20],
    'gräddlikör': all_categories[21],
    'ägglikör': all_categories[21],
    'kryddlikör': all_categories[22],
    'örtlikör': all_categories[22],
    'likör': all_categories[23],
    'madeira': all_categories[24],
    'mjöd': all_categories[25],
    'montilla': all_categories[26],
    'mousserande vin': all_categories[27],
    'champagne': all_categories[27],
    'vodka': all_categories[28],
    'portvin': all_categories[29],
    'punsch': all_categories[30],
    'ljus rom': all_categories[31],
    'mörk rom': all_categories[32],
    'rom': all_categories[33],
    'rosé': all_categories[34],
    'rosévin': all_categories[34],
    'vin': all_categories[35],
    'rött vin': all_categories[35],
    'sake': all_categories[36],
    'sherry': all_categories[37],
    'smaksatt sprit': all_categories[38],
    'smaksatt vin': all_categories[39],
    'sprit av frukt': all_categories[40],
    'tequila': all_categories[41],
    'mezcal': all_categories[41],
    'vermouth': all_categories[42],
    'vin av flera typer': all_categories[43],
    'vitt vin': all_categories[44],
    'whisky': all_categories[45],
    'whiskey': all_categories[45],
    'öl': all_categories[46],
    'ljus öl': all_categories[47],
    'mörk öl': all_categories[48],
    'övrig sprit': all_categories[49],
    'övrigt starkvin': all_categories[50],
}

all_types = specific_type_mappings.keys()