# -*- coding: utf-8 -*-

def change_category(category): 
	if category in category_mappings:
		return category_mappings[category]
	return category

categories = {
    1 : unicode(u'Alkoholfritt'),
    2 : unicode(u'Aniskryddad sprit'),
    3 : unicode(u'Aperitif'),
    4 : unicode(u'Armagnac'),
    5 : unicode(u'Bitter'),
    6 : unicode(u'Blanddrycker'),
    7 : unicode(u'Brandy'),
    8 : unicode(u'Vinsprit'),
    9 : unicode(u'Calvados'),
    10 : unicode(u'Cider'),
    11 : unicode(u'Cognac, Konjak'),
    12 : unicode(u'Drinkar och Cocktails'),
    13 : unicode(u'Fruktvin'),
    14 : unicode(u'Genever'),
    15 : unicode(u'Gin'),
    16 : unicode(u'Glögg och Glühwein'),
    17 : unicode(u'Grappa'),
    18 : unicode(u'Kryddad sprit'),
    19 : unicode(u'Kaffelikör, Chokladlikör'),
    20 : unicode(u'Fruktlikör, Bärlikör'),
    21 : unicode(u'Gräddlikör, Ägglikör'),
    22 : unicode(u'Kryddlikör, Örtlikör'),
    23 : unicode(u'Likör'),
    24 : unicode(u'Madeira'),
    25 : unicode(u'Mjöd'),
    26 : unicode(u'Montilla'),
    27 : unicode(u'Mousserande vin, Champagne'),
    28 : unicode(u'Vodka'),
    29 : unicode(u'Portvin'),
    30 : unicode(u'Punsch'),
    31 : unicode(u'Rom, Ljus rom'),
    32 : unicode(u'Rom, Mörk rom'),
    33 : unicode(u'Rom'),
    34 : unicode(u'Rosé, Rosévin'),
    35 : unicode(u'Vin, Rött vin'),
    36 : unicode(u'Sake'),
    37 : unicode(u'Sherry'),
    38 : unicode(u'Smaksatt sprit'),
    39 : unicode(u'Smaksatt vin'),
    40 : unicode(u'Sprit av frukt'),
    41 : unicode(u'Tequila, Mezcal'),
    42 : unicode(u'Vermouth'),
    43 : unicode(u'Vin av flera typer'),
    44 : unicode(u'Vin, Vitt vin'),
    45 : unicode(u'Whisky, Whiskey'),
    46 : unicode(u'Öl'),
    47 : unicode(u'Öl, Ljus öl'),
    48 : unicode(u'Öl, Mörk öl'),
    49 : unicode(u'Övrig sprit'),
    50 : unicode(u'Övrigt starkvin'),
}

# maps systembolagets categories to more general ones
category_mappings = {
    unicode(u'Alkoholfritt, Aperitif och Bitter') : categories[1],
    unicode(u'Alkoholfritt, Cider') : categories[1],
    unicode(u'Alkoholfritt, Glögg') : categories[1],
    unicode(u'Alkoholfritt, Mousserande') : categories[1],
    unicode(u'Alkoholfritt, Mousserande') : categories[1],
    unicode(u'Alkoholfritt, Must') : categories[1],
    unicode(u'Alkoholfritt, Rosé') : categories[1],
    unicode(u'Alkoholfritt, Rött') : categories[1],
    unicode(u'Alkoholfritt, Vatten') : categories[1],
    unicode(u'Alkoholfritt, Vitt') : categories[1],
    unicode(u'Alkoholfritt, Öl') : categories[1],
    unicode(u'Alkoholfritt, Övrigt') : categories[1],
    unicode(u'Aniskryddad sprit') : categories[2],
    unicode(u'Aperitif') : categories[3],
    unicode(u'Armagnac') : categories[4],
    unicode(u'Bitter') : categories[5],
    unicode(u'Blanddrycker') : categories[6],
    unicode(u'Brandy och Vinsprit, Brandy') : categories[7],
    unicode(u'Brandy och Vinsprit, Vinsprit') : categories[8],
    unicode(u'Calvados') : categories[9],
    unicode(u'Cider') : categories[10],
    unicode(u'Cider, Söt') : categories[10],
    unicode(u'Cider, Torr och halvtorr') : categories[10],
    unicode(u'Cognac') : categories[11],
    unicode(u'Drinkar och Cocktails') : categories[12],
    unicode(u'Fruktvin') : categories[13],
    unicode(u'Fruktvin, Sött') : categories[13],
    unicode(u'Fruktvin, Torrt') : categories[13],
    unicode(u'Genever') : categories[14],
    unicode(u'Gin') : categories[15],
    unicode(u'Glögg och Glühwein') : categories[16],
    unicode(u'Grappa och Marc') : categories[17],
    unicode(u'Grappa och Marc, Grappa') : categories[17],
    unicode(u'Grappa och Marc, Marc') : categories[17],
    unicode(u'Kryddad sprit') : categories[18], 
    unicode(u'Likör, Choklad-, kaffe- och nötter') : categories[19],
    unicode(u'Likör, Frukter och bär') : categories[20],
    unicode(u'Likör, Grädde och ägg') : categories[21],
    unicode(u'Likör, Kryddor och örter') : categories[22],
    unicode(u'Likör, Övrig') : categories[23],
    unicode(u'Madeira') : categories[24],
    unicode(u'Madeira, Bual') : categories[24],
    unicode(u'Madeira, Malvoisie/Malmsey') : categories[24],
    unicode(u'Madeira, Sercial') : categories[24],
    unicode(u'Madeira, Övrig') : categories[24],
    unicode(u'Mjöd') : categories[25], 
    unicode(u'Montilla') : categories[26],
    unicode(u'Mousserande vin') : categories[27],
    unicode(u'Mousserande vin, Rosé') : categories[27],
    unicode(u'Mousserande vin, Rött') : categories[27],
    unicode(u'Mousserande vin, Vitt  halvtorrt') : categories[27],
    unicode(u'Mousserande vin, Vitt sött') : categories[27],
    unicode(u'Mousserande vin, Vitt torrt') : categories[27],
    unicode(u'Mousserande vin, Övrigt') : categories[27],
    unicode(u'Okryddad sprit') : categories[28],
    unicode(u'Portvin, Rosé') : categories[29],
    unicode(u'Portvin, Rött') : categories[29],
    unicode(u'Portvin, Vitt') : categories[29],
    unicode(u'Punsch') : categories[30],
    unicode(u'Rom, Ljus') : categories[31],
    unicode(u'Rom, Mörk') : categories[32],
    unicode(u'Rom, Smaksatt') : categories[33],
    unicode(u'Rosévin') : categories[34],
    unicode(u'Rött vin') : categories[35],
    unicode(u'Rött vin, Fruktigt & Smakrikt') : categories[35],
    unicode(u'Rött vin, Kryddigt & Mustigt') : categories[35],
    unicode(u'Rött vin, Mjukt & Bärigt') : categories[35],
    unicode(u'Rött vin, Stramt & Nyanserat') : categories[35], 
    unicode(u'Rött vin, Sött') : categories[35], 
    unicode(u'Sake') : categories[36],
    unicode(u'Sherry') : categories[37],
    unicode(u'Sherry, Halvtorr') : categories[37],
    unicode(u'Sherry, Söt') : categories[37], 
    unicode(u'Sherry, Torr') : categories[37],
    unicode(u'Smaksatt sprit') : categories[38],
    unicode(u'Smaksatt vin') : categories[39],
    unicode(u'Sprit av frukt') : categories[40],
    unicode(u'Tequila och Mezcal') : categories[41],
    unicode(u'Vermouth, Rosé') : categories[42],
    unicode(u'Vermouth, Röd söt') : categories[42],
    unicode(u'Vermouth, Vit söt') : categories[42],
    unicode(u'Vermouth, Vit torr') : categories[42],
    unicode(u'Vin av flera typer') : categories[43],
    unicode(u'Vitt vin') : categories[44],
    unicode(u'Vitt vin, Halvtorrt, Druvigt & Blommigt') : categories[44],
    unicode(u'Vitt vin, Halvtorrt, Friskt & Fruktigt') : categories[44],
    unicode(u'Vitt vin, Halvtorrt, Lätt & Avrundat') : categories[44],
    unicode(u'Vitt vin, Sött') : categories[44],
    unicode(u'Vitt vin, Torrt, Druvigt & Blommigt') : categories[44],
    unicode(u'Vitt vin, Torrt, Friskt & Fruktigt') : categories[44],
    unicode(u'Vitt vin, Torrt, Fylligt & Smakrikt') : categories[44],
    unicode(u'Vitt vin, Torrt, Lätt & Avrundat') : categories[44],
    unicode(u'Whisky, Blended') : categories[45],
    unicode(u'Whisky, Bourbon') : categories[45], 
    unicode(u'Whisky, Grain') : categories[45],
    unicode(u'Whisky, Malt') : categories[45],
    unicode(u'Whisky, Rye') :  categories[45],
    unicode(u'Whisky, Övrig') : categories[45],
    unicode(u'Öl, Ale') : categories[46],
    unicode(u'Öl, Flera typer') : categories[46],
    unicode(u'Öl, Ljus lager') : categories[47],
    unicode(u'Öl, Mörk lager') : categories[48],
    unicode(u'Öl, Porter och Stout') : categories[46],
    unicode(u'Öl, Specialöl') : categories[46],
    unicode(u'Öl, Spontanjäst öl') : categories[46],
    unicode(u'Öl, Veteöl') : categories[46],
    unicode(u'Övrig sprit') : categories[49],
    unicode(u'Övrigt starkvin') : categories[50]
}